Repository ansible-collections/ansible.netcommon, pull requests merged in 2021-02, with the labels that each got.

#183 Remove deprecated options from netconf_config
  .gitignore
  changelogs/fragments/remove-netconf_config-args.yaml
  docs/ansible.netcommon.netconf_config_module.rst
  plugins/doc_fragments/netconf.py
  plugins/modules/netconf_config.py
  tests/integration/targets/prepare_iosxe_tests/tasks/main.yml
  tests/unit/plugins/action/cli_parse/fixtures/nxos_show_version.txt
  tests/unit/plugins/cli_parsers/fixtures/nxos_show_version.cfg
Labels: blocks_release, breaking, gate

#213 Assorted documentation fixes
  changelogs/fragments/213-docs-updates.yaml
  docs/ansible.netcommon.net_l3_interface_module.rst
  docs/ansible.netcommon.net_vrf_module.rst
  plugins/modules/net_l3_interface.py
  plugins/modules/net_vrf.py
Labels: docs, gate

#215 Drop verbose flag from tox's call to black
  tox.ini
Labels: gate

#216 Add custom filters `any` and `all` for j2
  changelogs/fragments/support_custom_filters.yaml
  plugins/module_utils/network/common/utils.py
Labels: gate

#93 Remove ipaddress from netcommon
  changelogs/fragments/93-remove-ipaddress.yaml
  plugins/module_utils/compat/ipaddress.py
  plugins/module_utils/network/common/facts/facts.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.9.txt
Labels: breaking, gate

#221 Fix ansible-test-sanity-docker failures
  changelogs/fragments/update_requires_ansible.yaml
  meta/runtime.yml
  tests/sanity/ignore-2.11.txt
Labels: gate

#222 Pin collection-prep to a real release
  .pre-commit-config.yaml
Labels: gate

#120 Add single_user_mode feature to network_cli
  changelogs/fragments/support_caching.yaml
  plugins/cache/__init__.py
  plugins/cache/memory.py
  plugins/connection/network_cli.py
Labels: blocks_release, feature, gate

#223 Address yamllint failures
  changelogs/fragments/93-remove-ipaddress.yaml
  changelogs/fragments/remove-netconf_config-args.yaml
  changelogs/fragments/support_caching.yaml
  changelogs/fragments/yamllint.yaml
  tests/integration/targets/netconf_config/tests/nxos/basic.yaml
  tests/integration/targets/netconf_rpc/tests/iosxr/basic.yaml
  tests/integration/targets/prepare_nxos_tests/tasks/main.yaml
  tox.ini
Labels: gate

#180 Expose connection class object to NetworkTemplate
  changelogs/fragments/180_RMbase_engine.yaml
  plugins/module_utils/network/common/network_template.py
  plugins/module_utils/network/common/resource_module.py
  plugins/module_utils/network/common/rm_base/network_template.py
  plugins/module_utils/network/common/rm_base/resource_module.py
  plugins/module_utils/network/common/rm_base/resource_module_base.py
Labels: bug, gate

#182 Update cli_parse plugins and testcase
  .yamllint
  README.md
  changelogs/fragments/182-cli_parse_deprecate.yaml
  docs/ansible.netcommon.native_cli_parsers.rst
  docs/ansible.netcommon.ntc_templates_cli_parsers.rst
  docs/ansible.netcommon.pyats_cli_parsers.rst
  galaxy.yml
  meta/runtime.yml
  plugins/action/cli_parse.py
  plugins/cli_parsers/json_parser.py
  plugins/cli_parsers/textfsm_parser.py
  plugins/cli_parsers/ttp_parser.py
  plugins/cli_parsers/xml_parser.py
  plugins/module_utils/cli_parser/cli_parserbase.py
  plugins/modules/cli_parse.py
  plugins/sub_plugins/cli_parser/native_parser.py
  plugins/sub_plugins/cli_parser/ntc_templates_parser.py
  plugins/sub_plugins/cli_parser/pyats_parser.py
  test-requirements.txt
  tests/integration/targets/cli_parse/tasks/argspec.yaml
  tests/integration/targets/cli_parse/tasks/centos_native.yaml
  tests/integration/targets/cli_parse/tasks/fedora_native.yaml
  tests/integration/targets/cli_parse/tasks/main.yaml
  tests/integration/targets/cli_parse/tasks/nxos_json.yaml
  tests/integration/targets/cli_parse/tasks/nxos_native.yaml
  tests/integration/targets/cli_parse/tasks/nxos_ntc_templates.yaml
  tests/integration/targets/cli_parse/tasks/nxos_pyats.yaml
  tests/integration/targets/cli_parse/tasks/nxos_textfsm.yaml
  tests/integration/targets/cli_parse/tasks/nxos_ttp.yaml
  tests/integration/targets/cli_parse/tasks/nxos_xml.yaml
  tests/sanity/ignore-2.9.txt
  tests/unit/plugins/action/cli_parse/test_cli_parse.py
  tests/unit/plugins/cli_parsers/fixtures/nxos_show_version.textfsm
  tests/unit/plugins/cli_parsers/fixtures/nxos_show_version_invalid.textfsm
  tests/unit/plugins/cli_parsers/test_json_parser.py
  tests/unit/plugins/cli_parsers/test_pyats_parser.py
  tests/unit/plugins/cli_parsers/test_textfsm_parser.py
  tests/unit/plugins/cli_parsers/test_xml_parser.py
Labels: blocks_release, bug, gate

#172 Add ansible_network_direct_execution
  changelogs/fragments/ansible_network_direct_execution.yaml
  docs/ansible.netcommon.httpapi_connection.rst
  docs/ansible.netcommon.netconf_connection.rst
  docs/ansible.netcommon.network_cli_connection.rst
  plugins/action/cli_command.py
  plugins/action/network.py
  plugins/connection/httpapi.py
  plugins/connection/netconf.py
  plugins/connection/network_cli.py
Labels: blocks_release, feature, gate

#212 Documentation for filter plugins?
  .pre-commit-config.yaml
  README.md
  changelogs/fragments/212-update-documentation.yaml
  docs/ansible.netcommon.network_cli_connection.rst
  plugins/filter/ipaddr.py
Labels: gate

#225 Move warning message for cli_config module
  changelogs/fragments/config_module_warning_msg.yaml
  plugins/modules/cli_config.py
Labels: gate

#217 Gracefully handle connection closing in pylibssh
  changelogs/fragments/217-pylibssh-conn-closed.yaml
  plugins/connection/network_cli.py
Labels: blocks_release, gate
