Repository ansible-collections/ansible.netcommon, pull requests merged in 2023-07, with the labels that each got.

#559 Release 5.1.2
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/549-connection-strings.yml
  changelogs/fragments/550-ansible-lint.yml
  changelogs/fragments/gha_release.yaml
  changelogs/fragments/line-length.yaml
  galaxy.yml
Labels: skip-changelog

#546 Vendor telnetlib from cpython
  .flake8
  LICENSES/PSF-2.0.txt
  changelogs/fragments/telnet.yaml
  plugins/action/telnet.py
  plugins/connection/libssh.py
  plugins/plugin_utils/compat/telnetlib.py
  pyproject.toml
  tests/sanity/ignore-2.12.txt
  tests/sanity/ignore-2.13.txt
  tests/sanity/ignore-2.14.txt
  tests/sanity/ignore-2.15.txt
  tests/sanity/ignore-2.16.txt
  tests/sanity/ignore-2.9.txt
Labels: bug

#572 Update codecov config to hopefully fix issues
  codecov.yml
Labels: skip-changelog

#573 Changelog updated
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/telnet.yaml
  galaxy.yml
Labels: skip-changelog

#569 Add default cliconf plugin good enough to use cli_command most of the time
  README.md
  changelogs/fragments/default-cliconf.yaml
  docs/ansible.netcommon.default_cliconf.rst
  plugins/cliconf/default.py
  plugins/connection/network_cli.py
  plugins/plugin_utils/cliconf_base.py
  tests/unit/plugins/cliconf/test_default.py
Labels: feature

#566 Indicate that ssh_args will be removed.
  changelogs/fragments/ssh_args.yaml
  docs/ansible.netcommon.libssh_connection.rst
  plugins/connection/libssh.py
  tests/unit/mock/loader.py
Labels: deprecated
