Repository ansible-collections/ansible.netcommon, pull requests merged in 2023-08, with the labels that each got.

#577 disable auto changelog PR on merge
  .github/workflows/push.yml
Labels: skip-changelog

#545 Add new options to httpapi connection
  changelogs/fragments/httpapi_options.yaml
  docs/ansible.netcommon.httpapi_connection.rst
  plugins/connection/httpapi.py
Labels: feature

#578 Segregate filter plugins
  .github/workflows/tests.yml
  .gitignore
  README.md
  changelogs/fragments/vlan_extender.yaml
  docs/ansible.netcommon.comp_type5_filter.rst
  docs/ansible.netcommon.hash_salt_filter.rst
  docs/ansible.netcommon.parse_cli_filter.rst
  docs/ansible.netcommon.parse_cli_textfsm_filter.rst
  docs/ansible.netcommon.parse_xml_filter.rst
  docs/ansible.netcommon.type5_pw_filter.rst
  docs/ansible.netcommon.vlan_expander_filter.rst
  docs/ansible.netcommon.vlan_parser_filter.rst
  plugins/filter/comp_type5.py
  plugins/filter/hash_salt.py
  plugins/filter/network.py
  plugins/filter/parse_cli.py
  plugins/filter/parse_cli_textfsm.py
  plugins/filter/parse_xml.py
  plugins/filter/type5_pw.py
  plugins/filter/vlan_expander.py
  plugins/filter/vlan_parser.py
  plugins/plugin_utils/comp_type5.py
  plugins/plugin_utils/hash_salt.py
  plugins/plugin_utils/parse_cli.py
  plugins/plugin_utils/parse_cli_textfsm.py
  plugins/plugin_utils/parse_xml.py
  plugins/plugin_utils/type5_pw.py
  plugins/plugin_utils/vlan_expander.py
  plugins/plugin_utils/vlan_parser.py
  tests/unit/plugins/filter/comp_type5.py
  tests/unit/plugins/filter/test_hash_salt.py
  tests/unit/plugins/filter/test_network.py
  tests/unit/plugins/filter/test_type5_pw.py
  tests/unit/plugins/filter/test_vlan_extender.py
  tests/unit/plugins/filter/test_vlan_parser.py
Labels: enhancement
