Repository ansible-collections/ansible.netcommon, pull requests merged in 2024-04, with the labels that each got.

#624 fix sanity run ansible.netcommon
  .flake8
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  plugins/plugin_utils/compat/telnetlib.py
  tests/sanity/ignore-2.18.txt
  tests/unit/mock/procenv.py
  tests/unit/module_utils/network/common/test_parsing.py
  tests/unit/modules/utils.py
  tests/unit/plugins/cli_parsers/test_pyats_parser.py
  tests/unit/plugins/filter/comp_type5.py
  tests/unit/plugins/filter/test_hash_salt.py
  tests/unit/plugins/filter/test_network.py
  tests/unit/plugins/filter/test_pop_ace.py
  tests/unit/plugins/filter/test_type5_pw.py
  tests/unit/plugins/filter/test_vlan_extender.py
  tests/unit/plugins/filter/test_vlan_parser.py
  tox.ini
Labels: skip-changelog

#618 Add cli_restore plugin
  README.md
  changelogs/fragments/add_cli_restore.yaml
  docs/ansible.netcommon.cli_restore_module.rst
  plugins/modules/cli_restore.py
Labels: blocks_release, enhancement

#627 Prepare release 6.1.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/626-verbosity.yml
  changelogs/fragments/add_cli_restore.yaml
  changelogs/fragments/verbosity.yml
  galaxy.yml
Labels: skip-changelog

#630 Exception handling when restore plugin not supported
  changelogs/fragments/update_not_supported_exception.yaml
  plugins/modules/cli_restore.py
Labels: bug
