Repository ansible-collections/ansible.netcommon, pull requests merged in 2024-05, with the labels that each got.

#634 Update test-req fixing CI issues
  .ansible-lint
  test-requirements.txt
Labels: skip-changelog

#613 Fix link to vyos.vyos collection
  README.md
Labels: bug

#635 Add new argument `err_responses` to edit_config in CliconfBase
  plugins/module_utils/network/common/rm_base/resource_module.py
  plugins/plugin_utils/cliconf_base.py
Labels: skip-changelog

#614 Fix module name and log consistency in parse_cli_textfsm filter doc
  changelogs/fragments/614-fix-parse_cli_textfsm-doc.yaml
  docs/ansible.netcommon.parse_cli_textfsm_filter.rst
  plugins/filter/parse_cli_textfsm.py
Labels: docs

#640 Revert edit_config signature updates in #653
  changelogs/fragments/bug_653.yaml
  plugins/module_utils/network/common/rm_base/resource_module.py
  plugins/plugin_utils/cliconf_base.py
Labels: bug

#642 Prepare for release v6.1.3
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/bug_653.yaml
Labels: skip-changelog
