Repository ansible-collections/ansible.netcommon, pull requests merged in 2024-06, with the labels that each got.

#595 Fix routeros net put
  changelogs/fragments/fix-routeros-net_put.yaml
  plugins/action/net_put.py
Labels: bug

#644 Bump min ansible-core version to 2.15.0
  README.md
  changelogs/fragments/min_215.yaml
  meta/runtime.yml
Labels: breaking

#646 Fix libssh get api call
  changelogs/fragments/libssh_get.yaml
  plugins/connection/libssh.py
Labels: bug

#648 Update galaxy.yml for v7.0.0
  galaxy.yml
Labels: skip-changelog

#649 update precommit ref `pre-commit/mirrors-prettier` to `pycontribs/mirrors-prettier`
  .pre-commit-config.yaml
Labels: skip-changelog

#650 Update tox-ansible.ini
  tox-ansible.ini
Labels: skip-changelog
